apiVersion: apps/v1
kind: Deployment
metadata:
  name: corderos-app
  namespace: corderos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corderos-app
  template:
    metadata:
      labels:
        app: corderos-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: corderos-app
        image: docker.io/kaligulix/21k-registry:corderos-app-v2
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256M"
            cpu: "200m"
          limits:
            memory: "512M" 
            cpu: "400m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: corderos-app-db
              key: DATABASE_URL
        ports:
        - containerPort: 8000
