apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: corderos-app
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com:21javi21/corderos-app.git
  ref:
    branch: main
  secretRef:
    name: flux-github-deploy
