apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: corderos
resources:
  - namespace.yaml
  - secret-ldap.yaml
  - postgres/
  - hall-of-hate-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - postgres-configmap.yaml
