apiVersion: v1
kind: ConfigMap
metadata:
  name: corderos-app-config
  namespace: corderos
data:
  DATABASE_URL: "postgresql://corderos_app:corderos_pass@postgres.corderos.svc.cluster.local:5432/corderos"