apiVersion: v1
kind: Secret
metadata:
  name: corderos-app-ldap
  namespace: corderos
type: Opaque
stringData:
  LDAP_URI: ldaps://ldap.kaligulix.com:636
  LDAP_BASE_DN: cn=users,dc=kaligulix,dc=com
  LDAP_BIND_DN: cn=admin,dc=kaligulix,dc=com
  LDAP_BIND_PASSWORD: "kaligulix"
  LDAP_GROUP_DN: cn=corderos,ou=Groups,dc=kaligulix,dc=com