apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secret-postgres.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
  - initdb-configmap.yaml
  - postgres-configmap.yaml
