apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: corderos
resources:
  - initdb-configmap.yaml
  - secret-postgres.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml

