apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres
  namespace: corderos
resources:
  - secret-postgres.yaml
  - statefulset-postgres.yaml
  - service-postgres.yaml
