apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  namespace: corderos
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.178.44
  selector:
    app: pgpool
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
