apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: corderos
spec:
  ports:
  - port: 5432
    targetPort: 5432
  clusterIP: None  # Para que funcione bien con StatefulSet
  selector:
    app: postgres
